# https://github.com/nushdev/nush-announcements/blob/0be1aa472448a74addb9735c943e5e2d68b45ad3/.github/workflows/build-compiled-data.yaml

name: Build compiled data on push
run-name: Build data for commit "${{ github.event.head_commit.message }}"
permissions:
  contents: write
on:
  push:
    branches:
    - main
    paths:
    - "v3/raw/*.json"
    - "!v3/raw/*/_*.json"
    - "!v3/raw/_*.json"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Build data
      run: node ./build/index.js
    - name: Commit and push
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions

        # The message for the commit.
        message: Build data (commit "${{ github.event.head_commit.message }}")
